[build-system]
requires = [ "setuptools >= 61.0", "setuptools-git-versioning>=2.0,<3"]
build-backend = "setuptools.build_meta"


[project]
name = "coker"
requires-python = ">=3.10"
dynamic = ["version"]
authors = [
    {name = "Peter Cudmore", email = "drpetercudmore@gmail.com"}
]
maintainers = [
     {name = "Peter Cudmore", email = "drpetercudmore@gmail.com"}
]
license="MPL-2.0"
license-files=["LICENSE.txt"]
classifiers = [

  "Development Status :: 3 - Alpha",

  # Indicate who your project is intended for
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Build Tools",

  # Specify the Python versions you support here.
  "Programming Language :: Python",

]
description = "Coker Mathematical Programming Toolkit"
readme = "README.md"
dependencies = [
    "numpy >= 2",
    "sympy",
    "scipy",
    "typing-extensions"
]



[project.optional-dependencies]
test = [
    "pytest < 5.0.0",
    "pytest-cov[all]"
]

lint = [
   "black == 25.1.0",
   "flake8"
]

ci = [
    "pytest < 5.0.0",
    "pytest-cov[all]",
    "black == 25.1.0",
    "flake8",
    "setuptools"
]
casadi = [
   "casadi",
]
jax = [
    "jax"
]

full = [
    "casadi",
    "jax"
]

[tool.pytest.ini_options]
minversion = "7.0"
pythonpath = ["src"]
testpaths = [
	"test",
]


[tool.black]
line-length = 79
target-version = ["py310", "py311", "py312"]