[build-system]
requires = [ "setuptools >= 61.0" ]
build-backend = "setuptools.build_meta"

dependencies = [
    "numpy",
    "sympy",
    "scipy",
    "dataclass-wizard"
]

[project]
name = "coker"
requires-python = ">=3.8"

dynamic = ["version"]

[project.optional-dependencies]
dev = [
    "pytest"
]

[tool.pytest.ini_options]
minversion = "7.0"
pythonpath = ["src"]
testpaths = [
	"test",
]
