"""Public deterministic artifact compilation for the Coker runtime."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import re
from types import MappingProxyType
from typing import Any, Mapping


@dataclass(frozen=True)
class ArtifactMetadata:
    """Runtime metadata for a compiled, directly mappable artifact."""

    name: str
    version: str
    function_id: int
    archive_alignment: int
    input_lengths: tuple[int, ...]
    output_lengths: tuple[int, ...]
    workspace_size: int | None = None
    required_workspace_size: int | None = None
    tangent_workspace_size: int | None = None
    qp_evaluator_workspace_size: int | None = None
    qp_tangent_workspace_size: int | None = None
    qp_coefficient_output_size: int | None = None
    qp_output_size: int | None = None
    qp_arena_bytes: int | None = None
    qp_arena_alignment: int | None = None

    @property
    def is_qp(self) -> bool:
        return self.qp_arena_bytes is not None

    @property
    def ordinary_workspace_size(self) -> int | None:
        return self.required_workspace_size

    @property
    def ordinary_tangent_workspace_size(self) -> int | None:
        return self.tangent_workspace_size

    @property
    def qp_output_length(self) -> int | None:
        return self.qp_output_size

    def as_dict(self) -> Mapping[str, Any]:
        """Return read-only metadata for deterministic code generation."""
        return MappingProxyType(
            {
                "name": self.name,
                "version": self.version,
                "function_id": self.function_id,
                "archive_alignment": self.archive_alignment,
                "input_lengths": self.input_lengths,
                "output_lengths": self.output_lengths,
                "workspace_size": self.workspace_size,
                "required_workspace_size": self.required_workspace_size,
                "tangent_workspace_size": self.tangent_workspace_size,
                "qp_evaluator_workspace_size": (
                    self.qp_evaluator_workspace_size
                ),
                "qp_tangent_workspace_size": self.qp_tangent_workspace_size,
                "qp_coefficient_output_size": (
                    self.qp_coefficient_output_size
                ),
                "qp_output_size": self.qp_output_size,
                "qp_arena_bytes": self.qp_arena_bytes,
                "qp_arena_alignment": self.qp_arena_alignment,
            }
        )


@dataclass(frozen=True)
class CompiledArtifact:
    """Immutable artifact bytes and the metadata read back from the runtime."""

    data: bytes
    metadata: ArtifactMetadata

    @property
    def bytecode(self) -> bytes:
        """Alias for the immutable mapped module bytes."""
        return self.data

    def write(self, path: str | Path) -> Path:
        """Write the artifact bytes without changing their content."""
        destination = Path(path)
        destination.write_bytes(self.data)
        return destination

    def rust_constants(self, module_name: str = "coker_artifact") -> str:
        """Generate deterministic Rust constants for this artifact."""
        identifier = _rust_identifier(module_name).upper()
        lines = [
            "// Generated by coker; do not edit.",
            (
                f"pub const {identifier}_FUNCTION_ID: u16 = "
                f"{self.metadata.function_id};"
            ),
            (
                f"pub const {identifier}_ARCHIVE_ALIGNMENT: usize = "
                f"{self.metadata.archive_alignment};"
            ),
            (
                f"pub const {identifier}_INPUT_LENGTHS: &[usize] = "
                f"&{list(self.metadata.input_lengths)!r};"
            ),
            (
                f"pub const {identifier}_OUTPUT_LENGTHS: &[usize] = "
                f"&{list(self.metadata.output_lengths)!r};"
            ),
            f"pub static {identifier}_BYTES: &[u8] = &[",
        ]
        for offset in range(0, len(self.data), 16):
            lines.append(
                "    "
                + ", ".join(
                    str(byte) for byte in self.data[offset : offset + 16]
                )
                + ","
            )
        lines.extend(
            [
                "];",
                "",
            ]
        )
        return "\n".join(lines)

    def write_rust_constants(
        self, path: str | Path, module_name: str = "coker_artifact"
    ) -> Path:
        """Write deterministic Rust constants for this artifact."""
        destination = Path(path)
        destination.write_text(
            self.rust_constants(module_name), encoding="utf-8", newline="\n"
        )
        return destination

    def write_artifact(
        self,
        artifact_path: str | Path,
        rust_constants_path: str | Path | None = None,
        module_name: str = "coker_artifact",
    ) -> tuple[Path, Path | None]:
        """Write `.coker` bytes and, optionally, the generated Rust module."""
        artifact = self.write(artifact_path)
        constants = (
            None
            if rust_constants_path is None
            else self.write_rust_constants(rust_constants_path, module_name)
        )
        return artifact, constants


def write_artifact(
    artifact: CompiledArtifact,
    artifact_path: str | Path,
    rust_constants_path: str | Path | None = None,
    module_name: str = "coker_artifact",
) -> tuple[Path, Path | None]:
    """Write an artifact and optional deterministic Rust constants module."""
    return artifact.write_artifact(
        artifact_path, rust_constants_path, module_name
    )


def _archive_alignment(data: bytes) -> int:
    if len(data) < 12:
        raise ValueError(
            "compiled artifact is shorter than its bytecode header"
        )
    return int.from_bytes(data[10:12], "little")


def _ordinary_metadata(
    data: bytes,
    info: Mapping[str, Any],
    function_id: int,
    name: str,
    version: str,
) -> ArtifactMetadata:
    required = int(info["required_workspace_size"])
    return ArtifactMetadata(
        name=name,
        version=version,
        function_id=int(function_id),
        archive_alignment=_archive_alignment(data),
        input_lengths=tuple(int(value) for value in info["input_specs"]),
        output_lengths=tuple(int(value) for value in info["output_specs"]),
        workspace_size=int(info["workspace_size"]),
        required_workspace_size=required,
        tangent_workspace_size=required,
    )


def _qp_metadata(
    data: bytes, info: Mapping[str, Any], name: str, version: str
) -> ArtifactMetadata:
    output_size = int(info["output_spec"])
    return ArtifactMetadata(
        name=name,
        version=version,
        function_id=int(info["function_id"]),
        archive_alignment=_archive_alignment(data),
        input_lengths=tuple(int(value) for value in info["input_specs"]),
        output_lengths=(output_size,),
        qp_evaluator_workspace_size=int(info["evaluator_workspace_size"]),
        qp_tangent_workspace_size=int(info["tangent_workspace_size"]),
        qp_coefficient_output_size=int(info["coefficient_output_size"]),
        qp_output_size=output_size,
        qp_arena_bytes=int(info["arena_bytes"]),
        qp_arena_alignment=int(info["arena_alignment"]),
    )


def _rust_identifier(value: str) -> str:
    result = re.sub(r"[^A-Za-z0-9_]", "_", value)
    if not result or result[0].isdigit():
        result = "_" + result


__all__ = [
    "ArtifactMetadata",
    "CompiledArtifact",
    "write_artifact",
]
