[package]
name = "coker-compiler"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
coker-bytecode = { path = "../coker-bytecode" }
coker-osqp-ffi = { path = "../coker-osqp-ffi" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
