name: Run Python tests

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Australia/Melbourne"
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install package
        run: poetry install --with ci,casadi,jax
      - name: Run tests
        run: poetry run pytest

  linter-name:
    name: runner / black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          use_pyproject: true
          options: '--check --diff src'